TRAIN:
  ENABLE: True
  DATASET: Drive_and_act
  BATCH_SIZE: 2
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /mnt/cephfs/dataset/m3lab_data/jialiang/mvit/part_RGB/checkpoints/checkpoint_epoch_00025.pyth #/mnt/cephfs/dataset/m3lab_data/wf_data/stts_pth/MViTv2_B_32x3_k400_f304025456.pyth #/mnt/cephfs/dataset/m3lab_data/jialiang/mvit/part_RGB/checkpoints/checkpoint_epoch_00025.pyth #
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 32
  SAMPLING_RATE: 3
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  # PATH_TO_DATA_DIR: path-to-k400-dir
  PATH_TO_DATA_DIR: /mnt/cephfs/home/alvin/wenfu/processing
  PATH_PREFIX: /mnt/cephfs/dataset/EPIC-KITCHENS-100/new/EPIC-KITCHENS
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  COLORJITTER: False  # new
Drive_and_act:
  VISUAL_DATA_DIR: /mnt/cephfs/dataset/m3lab_data/Drive-act-event/label
  ANNOTATIONS_DIR: /mnt/cephfs/dataset/m3lab_data/Drive-act-event/label
  PROMPT_DATA_DIR: /mnt/cephfs/dataset/m3lab_data/Drive-act-event/label/part-kinect_ir
  EVENT_PATH: /mnt/cephfs/dataset/Drive-Act-dataset/a-column-co-driver/kinect_ir #/mnt/cephfs/dataset/Drive-Act-dataset/a-column-co-driver/kinect_ir,/mnt/cephfs/dataset/m3lab_data/Drive-act-event
  TRAIN_MODE: prompt_fintuning #prompt_fintuning ,pretrain_event,pretrain_rgb
  TRAIN_LIST: part_split0_train.txt
  VAL_LIST: part_split0_val.txt
  TEST_LIST: part_split0_test.txt
MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 24
  BLOCK_DEPTHS: [0, 3, 6, 22] #[0, 3, 6, 22] ,None
  PROMPT_TYPE: vipt_deep #vipt_deep  None
  INPUT_MODAL: RGBIR                #EVENT,RGB,RGBE,RGBIR,IR
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.3
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 1, 1], [2, 1, 2, 2], [3, 1, 1, 1], [4, 1, 1, 1], [5, 1, 2, 2], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 1, 1], [15, 1, 1, 1], [16, 1, 1, 1], [17, 1, 1, 1], [18, 1, 1, 1], [19, 1, 1, 1], [20, 1, 1, 1], [21, 1, 2, 2], [22, 1, 1, 1], [23, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: False ##
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 15.0
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 34
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: cross_entropy # soft_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: Drive_and_act
  BATCH_SIZE: 2
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5
  CHECKPOINT_FILE_PATH: /mnt/cephfs/dataset/m3lab_data/jialiang/mvit/part_prompt_b4_drop0.3_freezelr4e-5/checkpoints/checkpoint_epoch_00029.pyth
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR:  /mnt/cephfs/dataset/m3lab_data/jialiang/mvit/debug
TENSORBOARD:
  ENABLE: True
